export const density = {
  tiny: { size: 400, sparse: 24, normal: 32, dense: 40, packed: 60 },
  small: { size: 800, sparse: 96, normal: 128, dense: 160, packed: 240 },
  medium: { size: 1200, sparse: 216, normal: 288, dense: 360, packed: 540 },
  large: { size: 1600, sparse: 384, normal: 512, dense: 640, packed: 910 },
  huge: { size: 2000, sparse: 600, normal: 800, dense: 940, packed: 945 }
}

export const planetFiles = ['9rvpjwoj.png', 'x5i1u2rd.png', 'at41td4j.png', 'n8dyfe9i.png', 'wjehz2lz.png']

export const names = [
  'Harper',
  'Tobolski',
  'Hollis',
  'Baxter',
  'Crockett',
  'Wiggins',
  'Wolden',
  'Carmain',
  'Perlich',
  'Clopton',
  'Lyons',
  'Willa',
  'Hortman',
  'Wichrowski',
  'Cicatello',
  'Reynolds',
  'Novak',
  'Hampton',
  'Rukavina',
  'Oganesian',
  'Mireles',
  'Huor',
  'Goutremout',
  'Groetsch',
  'Chabaud',
  'Fyffe',
  'Habermann',
  'Manikas',
  'Lebedeff',
  'Scharnberg',
  'Weeks',
  'Creed',
  'Clayton',
  'Hayes',
  'Schaefer',
  'Rush',
  'Harman',
  'Hudson',
  'Wilcox',
  '14 Coli',
  'Ajar',
  'Albemuth',
  'Allenby',
  'Almagest',
  'Almighty',
  'Applegate',
  'April',
  'Arcade',
  'Awk',
  'Axelrod',
  'Baker',
  'Bakwele',
  'Balder',
  'Berry',
  'Birthmark',
  'Blue Giant',
  'Bob',
  'Bonaparte',
  'Bones',
  'Bonus',
  'Braddock',
  'Burgoyne',
  'Calcium',
  'Cambridge',
  'Cancer',
  'Carter',
  'Chennault',
  'Chubs',
  'Chunk',
  'Cinnamon',
  'Coda',
  'Continental',
  'Cootie',
  'County Seat',
  'Covenant',
  'Crazy Horse',
  'Croce',
  'Crow',
  'Data',
  'Dayan',
  'Delta Delta Delta',
  'Devon IV',
  'Dewey',
  'Dingly Dell',
  'Dive',
  'Dowding',
  'Dwarte',
  'Dyson',
  'Elron',
  'Elsinore',
  'Emperium Gate',
  'Empty',
  'Flint Stone',
  'Floyd',
  'Fluffy',
  'Foamytap',
  'Forest',
  "Foucault's World",
  'Fox Trot',
  'Gaia 2',
  'Galbraith',
  'Gangtok',
  'Geronimo',
  'Greene',
  'Hammer',
  'Harding',
  'Heaven',
  'Hexnut',
  'Hiho',
  'Hollywood',
  'Hope',
  'Hunt',
  'Iceball',
  'Inferno',
  'Iodine',
  'Kaa',
  'Kirkland',
  'Kludge',
  'La Te Da',
  'Lafayette',
  'Lambda',
  'Lee',
  'Lever',
  'Linq',
  'Luscious',
  'Lyra',
  'Mamie',
  'Marion',
  'Mayberry',
  'Meade',
  'Medusa',
  'Melthorne',
  'Mirror',
  'Molybdenum',
  'Montgomery',
  'Myopus',
  'Nebulae',
  'Nirvana',
  'Notorious',
  'Oh Ho Ho',
  'Old',
  'Parsley',
  'Patton',
  'Penance',
  'Pershing',
  'Phi',
  'Phicol',
  'Pirate',
  'Planet 10',
  'PreVious',
  'Prune',
  'Purgatory',
  'Pyxidis',
  'Recalc',
  'Right',
  'Rommel',
  'Rubber',
  'Saada',
  'Sagittarius',
  'Salamander',
  'Shanty',
  'Sigma',
  'Skloot',
  'Slime',
  'Slinky',
  'Smorgasbord',
  'Spaatz',
  'Spay',
  'Spitfire',
  'Sputnik',
  'Status',
  'Stilton',
  'Stilwell',
  'Stove Top',
  'Taurus',
  'Tongue',
  'Trial',
  'Trismegistus',
  'Tull',
  'Underdog',
  'Uranium',
  'Valhalla',
  'Vanilla',
  'Veritas',
  'Vista',
  "Whistler's Mother",
  'Who',
  'Winken',
  'Winkle',
  'Woozle',
  'Worm',
  'Xenon',
  'X-Ray',
  'Y-Has',
  'Zero'
]

export const slotTypes = { weapon: 0, mech: 1, engine: 2, elect: 3, armor: 4, bomb: 5, shield: 6, mines: 7, scanner: 8 }
export const hullTypes = {
  Colonizer: [
    {
      name: 'Mini-Colony Ship',
      fuel: 150,
      armor: 10,
      initiative: 0,
      mass: 8,
      resoures: 3,
      exclusive: ['HE'],
      layout: [
        { component: ['Engine'], needs: 1, placement: { x: 0, y: 0 } },
        { component: ['Cargo'], capacity: 10, placement: { x: 2, y: 0 } },
        { component: ['Mech'], upto: 1, placement: { x: 4, y: 0 } }
      ]
    },
    {
      name: 'Colony Ship',
      fuel: 200,
      armor: 20,
      initiative: 0,
      mass: 20,
      resoures: 20,
      layout: [
        { component: ['Engine'], needs: 1, placement: { x: 0, y: 0 } },
        { component: ['Cargo'], capacity: 25, placement: { x: 2, y: 0 } },
        { component: ['Mech'], upto: 1, placement: { x: 4, y: 0 } }
      ]
    }
  ],
  Scout: [
    {
      name: 'Scout',
      fuel: 50,
      armor: 20,
      initiative: 1,
      mass: 8,
      resoures: 10,
      layout: [
        { component: ['Engine'], needs: 1, placement: { x: 0, y: 0 } },
        { component: ['General Purpose'], upto: 1, placement: { x: 2, y: 0 } },
        { component: ['Scanner'], upto: 1, placement: { x: 4, y: 0 } }
      ]
    },
    {
      name: 'Frigate',
      fuel: 125,
      armor: 45,
      initiative: 4,
      mass: 8,
      resoures: 12,
      tech: { con: 6 },
      layout: [
        { component: ['Engine'], needs: 1, placement: { x: 0, y: 0 } },
        { component: ['Shield', 'Armor'], upto: 2, placement: { x: 2, y: 0 } },
        { component: ['General Purpose'], upto: 3, placement: { x: 4, y: 0 } },
        { component: ['Scanner'], upto: 2, placement: { x: 6, y: 0 } }
      ]
    },
    {
      name: 'Destroyer',
      fuel: 280,
      armor: 200,
      initiative: 3,
      mass: 30,
      resoures: 35,
      tech: { con: 3 },
      layout: [
        { component: ['Engine'], needs: 1, placement: { x: 0, y: 3 } },
        { component: ['Armor'], upto: 2, placement: { x: 2, y: 3 } },
        { component: ['General Purpose'], upto: 1, placement: { x: 4, y: 3 } },
        { component: ['Mech'], upto: 1, placement: { x: 1, y: 1 } },
        { component: ['Elect'], upto: 1, placement: { x: 1, y: 5 } },
        { component: ['Weapon'], upto: 1, placement: { x: 3, y: 0 } },
        { component: ['Weapon'], upto: 1, placement: { x: 3, y: 6 } }
      ]
    }
  ]
}
